[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["cd crypto-billionaire-bot && npm ci"]

[phases.build]
cmds = ["cd crypto-billionaire-bot && npm run build --if-present"]

[start]
cmd = "cd crypto-billionaire-bot && npm start"
