-- ============================================================
-- BILLIONAIRE CRYPTO INTELLIGENCE BOT - DATABASE SCHEMA
-- All timestamps stored in UTC
-- Display timezone: Asia/Kolkata
-- ============================================================

-- Extension for UUID generation
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================================
-- CORE TABLES
-- ============================================================

-- Historical significant events (market crashes, halvings, ATHs, etc.)
CREATE TABLE IF NOT EXISTS historical_events (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    event_date DATE NOT NULL,
    event_type VARCHAR(50) NOT NULL, -- 'halving', 'crash', 'ath', 'regulation', 'hack', 'launch'
    symbol VARCHAR(20) DEFAULT 'BTC',
    description TEXT,
    price_at_event DECIMAL(20, 8),
    significance INTEGER DEFAULT 5 CHECK (significance BETWEEN 1 AND 10),
    metadata JSONB DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Predictions generated by the system
CREATE TABLE IF NOT EXISTS predictions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    symbol VARCHAR(20) NOT NULL DEFAULT 'BTCUSDT',
    timeframe VARCHAR(10) NOT NULL, -- '1m', '5m', '15m', '1h', '4h', '1d'
    prediction_type VARCHAR(30) NOT NULL, -- 'gann_level', 'cycle_turn', 'angle_break', 'composite'
    direction VARCHAR(10), -- 'bullish', 'bearish', 'neutral'
    entry_price DECIMAL(20, 8),
    target_price DECIMAL(20, 8),
    stop_price DECIMAL(20, 8),
    confidence_score DECIMAL(5, 4) CHECK (confidence_score BETWEEN 0 AND 1),
    features_used JSONB DEFAULT '{}',
    rationale TEXT,
    valid_from TIMESTAMPTZ NOT NULL,
    valid_until TIMESTAMPTZ NOT NULL,
    outcome VARCHAR(20), -- 'hit_target', 'hit_stop', 'expired', 'pending'
    outcome_price DECIMAL(20, 8),
    outcome_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Daily intelligence briefings
CREATE TABLE IF NOT EXISTS daily_briefings (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    briefing_date DATE NOT NULL UNIQUE,
    symbol VARCHAR(20) NOT NULL DEFAULT 'BTCUSDT',
    open_price DECIMAL(20, 8),
    gann_analysis JSONB NOT NULL,
    cycle_analysis JSONB NOT NULL,
    key_levels JSONB NOT NULL, -- {support: [], resistance: []}
    market_bias VARCHAR(20), -- 'strongly_bullish', 'bullish', 'neutral', 'bearish', 'strongly_bearish'
    summary TEXT,
    alerts JSONB DEFAULT '[]',
    delivered_at TIMESTAMPTZ,
    chat_ids_delivered JSONB DEFAULT '[]',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Weekly war room analysis (deeper analysis)
CREATE TABLE IF NOT EXISTS weekly_war_rooms (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    week_start DATE NOT NULL,
    week_end DATE NOT NULL,
    symbol VARCHAR(20) NOT NULL DEFAULT 'BTCUSDT',
    weekly_open DECIMAL(20, 8),
    weekly_close DECIMAL(20, 8),
    weekly_high DECIMAL(20, 8),
    weekly_low DECIMAL(20, 8),
    gann_weekly_analysis JSONB NOT NULL,
    cycle_convergences JSONB DEFAULT '[]',
    major_levels JSONB NOT NULL,
    weekly_forecast JSONB NOT NULL,
    performance_review JSONB DEFAULT '{}', -- review of last week's predictions
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(week_start, symbol)
);

-- Price history for analysis
CREATE TABLE IF NOT EXISTS price_history (
    id BIGSERIAL PRIMARY KEY,
    timestamp TIMESTAMPTZ NOT NULL,
    symbol VARCHAR(20) NOT NULL DEFAULT 'BTCUSDT',
    source VARCHAR(30) NOT NULL DEFAULT 'binance', -- 'binance', 'coingecko', 'manual'
    open_price DECIMAL(20, 8),
    high_price DECIMAL(20, 8),
    low_price DECIMAL(20, 8),
    close_price DECIMAL(20, 8) NOT NULL,
    volume DECIMAL(30, 8),
    timeframe VARCHAR(10) DEFAULT '1m',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- User settings for Telegram users
CREATE TABLE IF NOT EXISTS user_settings (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    chat_id BIGINT NOT NULL UNIQUE,
    username VARCHAR(100),
    display_timezone VARCHAR(50) DEFAULT 'Asia/Kolkata',
    preferred_symbols JSONB DEFAULT '["BTCUSDT"]',
    alert_preferences JSONB DEFAULT '{"daily_briefing": true, "level_alerts": true, "cycle_alerts": true}',
    risk_profile VARCHAR(20) DEFAULT 'moderate', -- 'conservative', 'moderate', 'aggressive'
    notification_hours JSONB DEFAULT '{"start": 8, "end": 22}', -- IST hours
    is_active BOOLEAN DEFAULT true,
    is_premium BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- LEARNING TABLES
-- ============================================================

-- Analysis snapshots - captures all features at a point in time
CREATE TABLE IF NOT EXISTS analysis_snapshots (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    snapshot_time TIMESTAMPTZ NOT NULL,
    symbol VARCHAR(20) NOT NULL DEFAULT 'BTCUSDT',
    price_at_snapshot DECIMAL(20, 8) NOT NULL,
    features JSONB NOT NULL, -- All computed features at this moment
    meta JSONB NOT NULL DEFAULT '{}', -- {timeframe, universe, symbol_scope, model_version}
    -- meta.timeframe: '1m', '5m', '15m', '1h', '4h', '1d'
    -- meta.universe: 'crypto', 'btc_only', 'altcoins'
    -- meta.symbol_scope: 'single', 'multi', 'correlated'
    tags JSONB DEFAULT '[]',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Outcome labels - actual results after snapshot
CREATE TABLE IF NOT EXISTS outcome_labels (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    snapshot_id UUID NOT NULL REFERENCES analysis_snapshots(id) ON DELETE CASCADE,
    horizon VARCHAR(10) NOT NULL, -- '1h', '4h', '24h'
    horizon_end_time TIMESTAMPTZ NOT NULL,
    price_at_horizon DECIMAL(20, 8),
    returns_percent DECIMAL(10, 6), -- percentage return
    direction_actual VARCHAR(10), -- 'up', 'down', 'flat'
    mae DECIMAL(10, 6), -- Maximum Adverse Excursion (worst drawdown during horizon)
    mfe DECIMAL(10, 6), -- Maximum Favorable Excursion (best profit during horizon)
    volatility_during DECIMAL(10, 6),
    labeled_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(snapshot_id, horizon)
);

-- Weight versions - model weights for scoring
CREATE TABLE IF NOT EXISTS weight_versions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    version_number SERIAL,
    weights JSONB NOT NULL, -- The actual weight values
    reason TEXT, -- Why this version was created
    performance_metrics JSONB DEFAULT '{}', -- backtested performance
    is_active BOOLEAN DEFAULT false,
    activated_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- INDEXES FOR PERFORMANCE
-- ============================================================

-- Historical events indexes
CREATE INDEX IF NOT EXISTS idx_historical_events_date ON historical_events(event_date);
CREATE INDEX IF NOT EXISTS idx_historical_events_type ON historical_events(event_type);
CREATE INDEX IF NOT EXISTS idx_historical_events_symbol ON historical_events(symbol);

-- Predictions indexes
CREATE INDEX IF NOT EXISTS idx_predictions_symbol ON predictions(symbol);
CREATE INDEX IF NOT EXISTS idx_predictions_created ON predictions(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_predictions_valid_range ON predictions(valid_from, valid_until);
CREATE INDEX IF NOT EXISTS idx_predictions_outcome ON predictions(outcome);
CREATE INDEX IF NOT EXISTS idx_predictions_type ON predictions(prediction_type);

-- Daily briefings indexes
CREATE INDEX IF NOT EXISTS idx_daily_briefings_date ON daily_briefings(briefing_date DESC);
CREATE INDEX IF NOT EXISTS idx_daily_briefings_symbol ON daily_briefings(symbol);

-- Weekly war rooms indexes
CREATE INDEX IF NOT EXISTS idx_weekly_war_rooms_dates ON weekly_war_rooms(week_start, week_end);
CREATE INDEX IF NOT EXISTS idx_weekly_war_rooms_symbol ON weekly_war_rooms(symbol);

-- Price history indexes (critical for performance)
CREATE INDEX IF NOT EXISTS idx_price_history_timestamp ON price_history(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_price_history_symbol_ts ON price_history(symbol, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_price_history_source ON price_history(source);
CREATE INDEX IF NOT EXISTS idx_price_history_symbol_source_ts ON price_history(symbol, source, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_price_history_timeframe ON price_history(timeframe);

-- User settings indexes
CREATE INDEX IF NOT EXISTS idx_user_settings_chat_id ON user_settings(chat_id);
CREATE INDEX IF NOT EXISTS idx_user_settings_active ON user_settings(is_active);

-- Analysis snapshots indexes (critical for learning)
CREATE INDEX IF NOT EXISTS idx_analysis_snapshots_time ON analysis_snapshots(snapshot_time DESC);
CREATE INDEX IF NOT EXISTS idx_analysis_snapshots_symbol ON analysis_snapshots(symbol);
CREATE INDEX IF NOT EXISTS idx_analysis_snapshots_symbol_time ON analysis_snapshots(symbol, snapshot_time DESC);
CREATE INDEX IF NOT EXISTS idx_analysis_snapshots_meta ON analysis_snapshots USING GIN(meta);
CREATE INDEX IF NOT EXISTS idx_analysis_snapshots_features ON analysis_snapshots USING GIN(features);
CREATE INDEX IF NOT EXISTS idx_analysis_snapshots_tags ON analysis_snapshots USING GIN(tags);

-- Outcome labels indexes
CREATE INDEX IF NOT EXISTS idx_outcome_labels_snapshot ON outcome_labels(snapshot_id);
CREATE INDEX IF NOT EXISTS idx_outcome_labels_horizon ON outcome_labels(horizon);
CREATE INDEX IF NOT EXISTS idx_outcome_labels_horizon_end ON outcome_labels(horizon_end_time DESC);
CREATE INDEX IF NOT EXISTS idx_outcome_labels_direction ON outcome_labels(direction_actual);

-- Weight versions indexes
CREATE INDEX IF NOT EXISTS idx_weight_versions_active ON weight_versions(is_active) WHERE is_active = true;
CREATE INDEX IF NOT EXISTS idx_weight_versions_created ON weight_versions(created_at DESC);

-- ============================================================
-- TRIGGERS FOR UPDATED_AT
-- ============================================================

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

DROP TRIGGER IF EXISTS update_historical_events_updated_at ON historical_events;
CREATE TRIGGER update_historical_events_updated_at
    BEFORE UPDATE ON historical_events
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_user_settings_updated_at ON user_settings;
CREATE TRIGGER update_user_settings_updated_at
    BEFORE UPDATE ON user_settings
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- ============================================================
-- DEFAULT DATA
-- ============================================================

-- Insert default weight version
INSERT INTO weight_versions (weights, reason, is_active, activated_at)
VALUES (
    '{
        "gann_sq9_weight": 0.25,
        "gann_angles_weight": 0.20,
        "cycle_major_weight": 0.20,
        "cycle_minor_weight": 0.10,
        "wheel24_weight": 0.15,
        "momentum_weight": 0.10,
        "level_proximity_bonus": 0.15,
        "cycle_convergence_bonus": 0.20
    }',
    'Initial default weights for composite scoring',
    true,
    NOW()
) ON CONFLICT DO NOTHING;

-- Insert some historical BTC events for cycle analysis
INSERT INTO historical_events (event_date, event_type, symbol, description, price_at_event, significance) VALUES
    ('2009-01-03', 'launch', 'BTC', 'Bitcoin Genesis Block', 0, 10),
    ('2012-11-28', 'halving', 'BTC', 'First Bitcoin Halving', 12.35, 10),
    ('2013-11-29', 'ath', 'BTC', 'First major ATH', 1163, 8),
    ('2014-02-24', 'crash', 'BTC', 'Mt. Gox Collapse', 550, 9),
    ('2016-07-09', 'halving', 'BTC', 'Second Bitcoin Halving', 650, 10),
    ('2017-12-17', 'ath', 'BTC', '2017 Bull Run ATH', 19783, 9),
    ('2018-12-15', 'crash', 'BTC', '2018 Bear Market Bottom', 3200, 8),
    ('2020-03-12', 'crash', 'BTC', 'COVID Black Thursday', 4800, 9),
    ('2020-05-11', 'halving', 'BTC', 'Third Bitcoin Halving', 8600, 10),
    ('2021-04-14', 'ath', 'BTC', 'Coinbase IPO ATH', 64800, 8),
    ('2021-11-10', 'ath', 'BTC', '2021 Cycle ATH', 69000, 9),
    ('2022-11-09', 'crash', 'BTC', 'FTX Collapse', 15800, 9),
    ('2024-01-10', 'regulation', 'BTC', 'Spot BTC ETF Approval', 46600, 9),
    ('2024-03-14', 'ath', 'BTC', 'Post-ETF ATH', 73700, 8),
    ('2024-04-20', 'halving', 'BTC', 'Fourth Bitcoin Halving', 64000, 10)
ON CONFLICT DO NOTHING;
